import type { Metadata } from 'next';
import localFont from 'next/font/local';
import NextTopLoader from 'nextjs-toploader';

import { MuiRtlThemeProvider, ReactQueryProvider } from '@shared/configs';

import './globals.css';

const vazirFont = localFont({
  src: './Vazirmatn[wght].woff2',
  display: 'swap',
  variable: '--font-vazir',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa" className={vazirFont.className}>
      <body>
        <NextTopLoader showSpinner={false} />
        <ReactQueryProvider>
          <MuiRtlThemeProvider>{children}</MuiRtlThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
